# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/s1645821/git/assessment2/Digital-Lab-4/Processor/Processor.cache/wt [current_project]
set_property parent.project_path /home/s1645821/git/assessment2/Digital-Lab-4/Processor/Processor.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files -quiet /home/s1645821/git/assessment2/Digital-Lab-4/Processor/Processor.runs/ila_1_synth_1/ila_1.dcp
set_property used_in_implementation false [get_files /home/s1645821/git/assessment2/Digital-Lab-4/Processor/Processor.runs/ila_1_synth_1/ila_1.dcp]
read_verilog -library xil_defaultlib {
  /home/s1645821/git/assessment2/Digital-Lab-4/Processor/Processor.srcs/sources_1/imports/Reset_Mouse.v
  /home/s1645821/git/assessment2/Digital-Lab-4/Processor/Processor.srcs/sources_1/imports/Remote_Mode.v
  /home/s1645821/git/assessment2/Digital-Lab-4/Processor/Processor.srcs/sources_1/imports/Read_Remote_Data.v
  /home/s1645821/git/assessment2/Digital-Lab-4/Processor/Processor.srcs/sources_1/imports/Mouse_Data.v
  /home/s1645821/git/assessment2/Digital-Lab-4/Processor/Processor.srcs/sources_1/imports/Microsoft_Mode.v
  /home/s1645821/git/assessment2/Digital-Lab-4/Processor/Processor.srcs/sources_1/imports/Data_Reporitng_Mode.v
  /home/s1645821/git/assessment2/Digital-Lab-4/Processor/Processor.srcs/sources_1/imports/Mouse_Coordinates.v
  /home/s1645821/git/assessment2/Digital-Lab-4/Processor/Processor.srcs/sources_1/imports/mouseTransmitter.v
  /home/s1645821/git/assessment2/Digital-Lab-4/Processor/Processor.srcs/sources_1/imports/mouseReciever.v
  /home/s1645821/git/assessment2/Digital-Lab-4/Processor/Processor.srcs/sources_1/imports/MouseMasterSM.v
  /home/s1645821/git/assessment2/Digital-Lab-4/Processor/Processor.srcs/sources_1/imports/imports/new/Mux_4_bit.v
  /home/s1645821/git/assessment2/Digital-Lab-4/Processor/Processor.srcs/sources_1/imports/imports/sources_1/imports/new/Generic_counter.v
  /home/s1645821/git/assessment2/Digital-Lab-4/Processor/Processor.srcs/sources_1/imports/Transceiver.v
  /home/s1645821/git/assessment2/Digital-Lab-4/Processor/Processor.srcs/sources_1/imports/MousePosition.v
  /home/s1645821/git/assessment2/Digital-Lab-4/Processor/Processor.srcs/sources_1/imports/Downloads/DecodingTheWorld_case.v
  /home/s1645821/git/assessment2/Digital-Lab-4/Processor/Processor.srcs/sources_1/imports/imports/new/Top.v
  /home/s1645821/git/assessment2/Digital-Lab-4/Processor/Processor.srcs/sources_1/imports/MouseWrapper.v
  /home/s1645821/git/assessment2/Digital-Lab-4/Processor/Processor.srcs/sources_1/new/ALU.v
  /home/s1645821/git/assessment2/Digital-Lab-4/Processor/Processor.srcs/sources_1/new/SEVEN_SEG_BUS_INTERFACE.v
  /home/s1645821/git/assessment2/Digital-Lab-4/Processor/Processor.srcs/sources_1/new/LEDs.v
  /home/s1645821/git/assessment2/Digital-Lab-4/Processor/Processor.srcs/sources_1/new/Timer.v
  /home/s1645821/git/assessment2/Digital-Lab-4/Processor/Processor.srcs/sources_1/new/ROM.v
  /home/s1645821/git/assessment2/Digital-Lab-4/Processor/Processor.srcs/sources_1/new/RAM.v
  /home/s1645821/git/assessment2/Digital-Lab-4/Processor/Processor.srcs/sources_1/new/Processor.v
  /home/s1645821/git/assessment2/Digital-Lab-4/Processor/Processor.srcs/sources_1/new/Mouse_Bus_Interface.v
  /home/s1645821/git/assessment2/Digital-Lab-4/Processor/Processor.srcs/sources_1/new/Processor_wrapper.v
}
read_xdc /home/s1645821/git/assessment2/Digital-Lab-4/Processor/Processor.srcs/constrs_1/imports/new/Wrapper.xdc
set_property used_in_implementation false [get_files /home/s1645821/git/assessment2/Digital-Lab-4/Processor/Processor.srcs/constrs_1/imports/new/Wrapper.xdc]

synth_design -top Processor_wrapper -part xc7a35tcpg236-1
write_checkpoint -noxdef Processor_wrapper.dcp
catch { report_utilization -file Processor_wrapper_utilization_synth.rpt -pb Processor_wrapper_utilization_synth.pb }
